#!/usr/bin/env python3

# this should not be imported
assert __name__ == '__main__'

# assure we are in the right directory, so we find our relative imports
import os
os.chdir(os.path.dirname(__file__))

import smtplib
from email.mime.text import MIMEText
from sys import stdin

import mailer
import my_logging

atexit.register(logging_shutdown)
logger = my_logging.getLogger('welcome_mailer')

logger.debug("Starting welcome mailer as user %d in group %d"%(os.geteuid(),os.getgid()))

mails = []

for line in stdin:
	pos = line.find(',')
	mail = line[:pos]
	pw = line[pos+1:]
	msg=MIMEText(pw)
	msg['Subject'] = 'Thunis Uberspace Passwort'
	msg['From'] = 'thunis-hostmaster@peacock.uberspace.de'
	msg['To'] = mail
	mails.append((msg,[mail]))

mailer.send_mails(mails)